# Generated by Django 5.2.15 on 2026-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_full_name', models.CharField(max_length=255, verbose_name='ФИО заявителя')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('help_description', models.TextField(verbose_name='Описание необходимой помощи')),
                ('people_needed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество людей')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('assigned', 'Назначена'), ('completed', 'Выполнена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_from', models.CharField(choices=[('public_form', 'Публичная форма'), ('admin_panel', 'Админ-панель'), ('volunteer_self', 'Волонтёр для себя'), ('volunteer_for_other', 'Волонтёр для другого')], default='public_form', max_length=40, verbose_name='Источник создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принята')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Отклонена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнена')),
                ('completion_comment', models.TextField(blank=True, verbose_name='Комментарий выполнения')),
                ('personal_data_agreed', models.BooleanField(default=False, verbose_name='Согласие на ПДн')),
                ('personal_data_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('personal_data_policy_version', models.CharField(blank=True, max_length=50, verbose_name='Версия политики ПДн')),
                ('applicant_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Новый статус')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('assigned', 'Назначен волонтёр'), ('completed', 'Выполнена'), ('pdf_generated', 'PDF сформирован'), ('exported', 'Экспортирована')], max_length=30, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'История заявки',
                'verbose_name_plural': 'История заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
