# Generated by Django 5.2.15 on 2026-07-05 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный волонтёр'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='applicationaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='applicationaction',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_actions', to=settings.AUTH_USER_MODEL, verbose_name='Волонтёр'),
        ),
        migrations.AddField(
            model_name='applicationaction',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено'),
        ),
    ]
