# Generated by Django 5.2.15 on 2026-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email заявителя'),
        ),
    ]
