# Generated by Django 5.2.15 on 2026-07-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applicant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('was_blocked', models.BooleanField(default=False, verbose_name='Заблокирована лимитом')),
                ('was_honeypot', models.BooleanField(default=False, verbose_name='Сработал honeypot')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Попытка отправки заявки',
                'verbose_name_plural': 'Попытки отправки заявок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='application_ip_addr_7f45a1_idx')],
            },
        ),
    ]
